Repository MicrosoftDocs/sql-docs.zh-cn, pull requests merged in 2018-11, with the labels that each got.

#40 Update download.md
  docs/azure-data-studio/download.md
Labels: Accepted, Linguistic Suggestion

#30 Update overview-sql-tools.md
  docs/tools/overview-sql-tools.md
Labels: Accepted, Linguistic Suggestion

#32 Update overview-sql-tools.md
  docs/tools/overview-sql-tools.md
Labels: Accepted, Linguistic Suggestion

#33 Update overview-sql-tools.md
  docs/tools/overview-sql-tools.md
Labels: In Progress

#34 Update overview-sql-tools.md
  docs/tools/overview-sql-tools.md
Labels: In Progress, Linguistic Suggestion

#35 Update overview-sql-tools.md
  docs/tools/overview-sql-tools.md
Labels: Accepted, Linguistic Suggestion

#38 Update what-is.md
  docs/azure-data-studio/what-is.md
Labels: Accepted, Linguistic Suggestion

#48 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#50 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#53 Update download.md
  docs/azure-data-studio/download.md
Labels: Accepted, Linguistic Suggestion

#63 是否可配置 -> 可配置
  docs/sql-server/install/file-locations-for-default-and-named-instances-of-sql-server.md
Labels: Accepted, Linguistic Suggestion

#42 Update tutorial-sql-editor.md
  docs/azure-data-studio/tutorial-sql-editor.md
Labels: In Progress, Linguistic Suggestion

#69 Update sql-server-r-services.md
  docs/advanced-analytics/r/sql-server-r-services.md
Labels: Accepted, Linguistic Suggestion

#44 Update sql-server-technical-documentation.md
  docs/sql-server/sql-server-technical-documentation.md
Labels: Accepted, Linguistic Suggestion

#45 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#47 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#51 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#52 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#71 Update r-server-standalone.md
  docs/advanced-analytics/r/r-server-standalone.md
Labels: Accepted, Linguistic Suggestion

#72 Update r-server-standalone.md
  docs/advanced-analytics/r/r-server-standalone.md
Labels: Accepted, Linguistic Suggestion

#37 Update what-is.md
  docs/azure-data-studio/what-is.md
Labels: Accepted, Linguistic Suggestion

#57 Update what-is-sql-server-machine-learning.md
  docs/advanced-analytics/what-is-sql-server-machine-learning.md
Labels: Accepted, Linguistic Suggestion

#73 Update sql-server-r-services.md
  docs/advanced-analytics/r/sql-server-r-services.md
Labels: Accepted, Linguistic Suggestion

#79 Fix typo
  docs/connect/php/pdo-prepare.md
Labels: Accepted, Linguistic Suggestion

#80 Fix typo
  docs/connect/jdbc/reference/getencrypt-method-sqlserverdatasource.md
Labels: Accepted, Linguistic Suggestion

#81 Fix typo
  docs/connect/jdbc/reference/rowupdated-method-sqlserverresultset.md
Labels: Accepted, Linguistic Suggestion

#82 Fix typo
  docs/integration-services/control-flow/execute-package-task.md
Labels: Accepted, Linguistic Suggestion

#74 Update sql-server-r-services.md
  docs/advanced-analytics/r/sql-server-r-services.md
Labels: Accepted, Linguistic Suggestion

#75 Update r-server-standalone.md
  docs/advanced-analytics/r/r-server-standalone.md
Labels: Accepted, Linguistic Suggestion
